name: spoco

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python 3.8
  - tqdm
  - pytorch
  - torchvision
  - tensorboard
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - hdbscan
  - pytest
